version: '2'
services:

  redmine:
    image: redmine
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: mysql
      REDMINE_DB_PASSWORD: redmine
    links:
      - mysql
    restart: always

  mysql:
    build: ./mysql
    restart: always

  ### 오피셜 저장소에 기록된 가이드에서는 마리아 디비를 사용한다. 근데 기본설정으로 할 경우 한글을 등록하는 과정에서 에러가 발생한다.
  ### 그래서 위에 기록된바와 같이 한글화 옵션을 지닌 mysql 이미지를 가지고 실행되도록 바꿔보았다.
  # mysql:
  #   image: mariadb
  #   environment:
  #     MYSQL_ROOT_PASSWORD: redmine
  #     MYSQL_DATABASE: redmine
  #   restart: always
